'use server'
import { Account, ActivateToken } from '@prisma/client'
import { sendEmail } from './sendEmail'

export const sendValidationEmail = async (newAccount: Account, token: ActivateToken) => {
	await sendEmail({
		to: newAccount.email,
		from: 'kontakt@mayestic.pl',
		subject: 'Activate your resee account.',
		message: `<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd"><html dir="ltr" xmlns="http://www.w3.org/1999/xhtml" xmlns:o="urn:schemas-microsoft-com:office:office" lang="en"><head><meta charset="UTF-8"><meta content="width=device-width, initial-scale=1" name="viewport"><meta name="x-apple-disable-message-reformatting"><meta http-equiv="X-UA-Compatible" content="IE=edge"><meta content="telephone=no" name="format-detection"><title>Empty template</title> <!--[if (mso 16)]><style type="text/css">     a {text-decoration: none;}     </style><![endif]--> <!--[if gte mso 9]><style>sup { font-size: 100% !important; }</style><![endif]--> <!--[if gte mso 9]><xml> <o:OfficeDocumentSettings> <o:AllowPNG></o:AllowPNG> <o:PixelsPerInch>96</o:PixelsPerInch> </o:OfficeDocumentSettings> </xml>
        <![endif]--><style type="text/css">.rollover:hover .rollover-first { max-height:0px!important; display:none!important; } .rollover:hover .rollover-second { max-height:none!important; display:block!important; } .rollover span { font-size:0px; } u + .body img ~ div div { display:none; } #outlook a { padding:0; } span.MsoHyperlink,span.MsoHyperlinkFollowed { color:inherit; mso-style-priority:99; } a.es-button { mso-style-priority:100!important; text-decoration:none!important; } a[x-apple-data-detectors] { color:inherit!important; text-decoration:none!important; font-size:inherit!important; font-family:inherit!important; font-weight:inherit!important; line-height:inherit!important; } .es-desk-hidden { display:none; float:left; overflow:hidden; width:0; max-height:0; line-height:0; mso-hide:all; } .es-button-border:hover > a.es-button { color:#ffffff!important; }
        @media only screen and (max-width:600px) {*[class="gmail-fix"] { display:none!important } p, a { line-height:150%!important } h1, h1 a { line-height:120%!important } h2, h2 a { line-height:120%!important } h3, h3 a { line-height:120%!important } h4, h4 a { line-height:120%!important } h5, h5 a { line-height:120%!important } h6, h6 a { line-height:120%!important } h1 { font-size:30px!important; text-align:left } h2 { font-size:24px!important; text-align:left } h3 { font-size:20px!important; text-align:left } h4 { font-size:24px!important; text-align:left } h5 { font-size:20px!important; text-align:left } h6 { font-size:16px!important; text-align:left } .es-header-body h1 a, .es-content-body h1 a, .es-footer-body h1 a { font-size:30px!important } .es-header-body h2 a, .es-content-body h2 a, .es-footer-body h2 a { font-size:24px!important } .es-header-body h3 a, .es-content-body h3 a, .es-footer-body h3 a { font-size:20px!important }
         .es-header-body h4 a, .es-content-body h4 a, .es-footer-body h4 a { font-size:24px!important } .es-header-body h5 a, .es-content-body h5 a, .es-footer-body h5 a { font-size:20px!important } .es-header-body h6 a, .es-content-body h6 a, .es-footer-body h6 a { font-size:16px!important } .es-menu td a { font-size:14px!important } .es-header-body p, .es-header-body a { font-size:14px!important } .es-content-body p, .es-content-body a { font-size:14px!important } .es-footer-body p, .es-footer-body a { font-size:14px!important } .es-infoblock p, .es-infoblock a { font-size:12px!important } .es-m-txt-c, .es-m-txt-c h1, .es-m-txt-c h2, .es-m-txt-c h3, .es-m-txt-c h4, .es-m-txt-c h5, .es-m-txt-c h6 { text-align:center!important } .es-m-txt-r, .es-m-txt-r h1, .es-m-txt-r h2, .es-m-txt-r h3, .es-m-txt-r h4, .es-m-txt-r h5, .es-m-txt-r h6 { text-align:right!important }
         .es-m-txt-j, .es-m-txt-j h1, .es-m-txt-j h2, .es-m-txt-j h3, .es-m-txt-j h4, .es-m-txt-j h5, .es-m-txt-j h6 { text-align:justify!important } .es-m-txt-l, .es-m-txt-l h1, .es-m-txt-l h2, .es-m-txt-l h3, .es-m-txt-l h4, .es-m-txt-l h5, .es-m-txt-l h6 { text-align:left!important } .es-m-txt-r img, .es-m-txt-c img, .es-m-txt-l img { display:inline!important } .es-m-txt-r .rollover:hover .rollover-second, .es-m-txt-c .rollover:hover .rollover-second, .es-m-txt-l .rollover:hover .rollover-second { display:inline!important } .es-m-txt-r .rollover span, .es-m-txt-c .rollover span, .es-m-txt-l .rollover span { line-height:0!important; font-size:0!important } .es-spacer { display:inline-table } a.es-button, button.es-button { font-size:18px!important; line-height:120%!important } a.es-button, button.es-button, .es-button-border { display:inline-block!important } .es-m-fw, .es-m-fw.es-fw, .es-m-fw .es-button { display:block!important }
         .es-m-il, .es-m-il .es-button, .es-social, .es-social td, .es-menu { display:inline-block!important } .es-adaptive table, .es-left, .es-right { width:100%!important } .es-content table, .es-header table, .es-footer table, .es-content, .es-footer, .es-header { width:100%!important; max-width:600px!important } .adapt-img { width:100%!important; height:auto!important } .es-mobile-hidden, .es-hidden { display:none!important } .es-desk-hidden { width:auto!important; overflow:visible!important; float:none!important; max-height:inherit!important; line-height:inherit!important } tr.es-desk-hidden { display:table-row!important } table.es-desk-hidden { display:table!important } td.es-desk-menu-hidden { display:table-cell!important } .es-menu td { width:1%!important } table.es-table-not-adapt, .esd-block-html table { width:auto!important } .es-social td { padding-bottom:10px } .h-auto { height:auto!important }
         .es-text-2366, .es-text-2366 p, .es-text-2366 a, .es-text-2366 h1, .es-text-2366 h2, .es-text-2366 h3, .es-text-2366 h4, .es-text-2366 h5, .es-text-2366 h6, .es-text-2366 ul, .es-text-2366 ol, .es-text-2366 li, .es-text-2366 span, .es-text-2366 sup, .es-text-2366 sub, .es-text-2366 u, .es-text-2366 b, .es-text-2366 strong, .es-text-2366 em, .es-text-2366 i { font-size:18px!important } .es-text-6177, .es-text-6177 p, .es-text-6177 a, .es-text-6177 h1, .es-text-6177 h2, .es-text-6177 h3, .es-text-6177 h4, .es-text-6177 h5, .es-text-6177 h6, .es-text-6177 ul, .es-text-6177 ol, .es-text-6177 li, .es-text-6177 span, .es-text-6177 sup, .es-text-6177 sub, .es-text-6177 u, .es-text-6177 b, .es-text-6177 strong, .es-text-6177 em, .es-text-6177 i { font-size:12px!important }
         .es-text-1595, .es-text-1595 p, .es-text-1595 a, .es-text-1595 h1, .es-text-1595 h2, .es-text-1595 h3, .es-text-1595 h4, .es-text-1595 h5, .es-text-1595 h6, .es-text-1595 ul, .es-text-1595 ol, .es-text-1595 li, .es-text-1595 span, .es-text-1595 sup, .es-text-1595 sub, .es-text-1595 u, .es-text-1595 b, .es-text-1595 strong, .es-text-1595 em, .es-text-1595 i { font-size:18px!important } .es-text-6177 .es-text-mobile-size-14, .es-text-6177 .es-text-mobile-size-14 * { font-size:14px!important; line-height:150%!important } }@media screen and (max-width:384px) {.mail-message-content { width:414px!important } }</style>
         </head> <body class="body" style="width:100%;height:100%;padding:0;Margin:0"><div dir="ltr" class="es-wrapper-color" lang="en" style="background-color:#F6F6F6"> <!--[if gte mso 9]><v:background xmlns:v="urn:schemas-microsoft-com:vml" fill="t"> <v:fill type="tile" color="#f6f6f6"></v:fill> </v:background><![endif]--><table class="es-wrapper" width="100%" cellspacing="0" cellpadding="0" role="none" style="mso-table-lspace:0pt;mso-table-rspace:0pt;border-collapse:collapse;border-spacing:0px;padding:0;Margin:0;width:100%;height:100%;background-repeat:repeat;background-position:center top;background-color:#F6F6F6"><tr><td valign="top" style="padding:0;Margin:0"><table class="es-content" cellspacing="0" cellpadding="0" align="center" role="none" style="mso-table-lspace:0pt;mso-table-rspace:0pt;border-collapse:collapse;border-spacing:0px;width:100%;table-layout:fixed !important"><tr>
        <td align="center" style="padding:0;Margin:0"><table class="es-content-body" cellspacing="0" cellpadding="0" bgcolor="#ffffff" align="center" style="mso-table-lspace:0pt;mso-table-rspace:0pt;border-collapse:separate;border-spacing:0px;background-color:#FFFFFF;width:600px" role="none"><tr><td align="left" style="padding:0;Margin:0;padding-top:20px;padding-right:20px;padding-left:20px;border-radius:5px"><table width="100%" cellspacing="0" cellpadding="0" role="none" style="mso-table-lspace:0pt;mso-table-rspace:0pt;border-collapse:collapse;border-spacing:0px"><tr><td valign="top" align="center" style="padding:0;Margin:0;width:560px"><table width="100%" cellspacing="0" cellpadding="0" role="presentation" style="mso-table-lspace:0pt;mso-table-rspace:0pt;border-collapse:collapse;border-spacing:0px"><tr>
        <td align="center" style="padding:0;Margin:0;padding-top:20px;padding-bottom:20px;font-size:0"><img src="https://efkbpey.stripocdn.email/content/guids/CABINET_4de024a55009967132822e25703de09c0c11697a629382eac566efae3f888978/images/logoo_xJj.png" alt="" class="adapt-img" style="display:block;font-size:14px;border:0;outline:none;text-decoration:none;border-radius:0" width="180" height="41"></td> </tr><tr><td align="left" style="padding:0;Margin:0;padding-top:20px;padding-bottom:20px"><h1 align="center" style="Margin:0;font-family:helvetica, 'helvetica neue', arial, verdana, sans-serif;mso-line-height-rule:exactly;letter-spacing:0;font-size:30px;font-style:normal;font-weight:normal;line-height:36px;color:#9357f4"><strong>Email verification</strong></h1></td></tr><tr>
        <td align="left" class="es-text-1595" style="padding:0;Margin:0;padding-top:10px;padding-bottom:10px"><p align="center" style="Margin:0;mso-line-height-rule:exactly;font-family:helvetica, 'helvetica neue', arial, verdana, sans-serif;line-height:27px;letter-spacing:0;color:#333333;font-size:18px">You created an account on resee Resume Creator. You have to validate your email address to activate your account. To activate, please click the following button:</p></td></tr> <tr>
        <td align="center" style="padding:0;Margin:0;padding-top:15px;padding-bottom:15px"> <!--[if mso]><a href="https://resee.vercel.app/activate/${token.token}" target="_blank" hidden> <v:roundrect xmlns:v="urn:schemas-microsoft-com:vml" xmlns:w="urn:schemas-microsoft-com:office:word" esdevVmlButton href="https://resee.vercel.app/activate/${token.token}" style="height:58px; v-text-anchor:middle; width:248px" arcsize="9%" stroke="f" fillcolor="#9357f4"> <w:anchorlock></w:anchorlock> <center style='color:#ffffff; font-family:helvetica, "helvetica neue", arial, verdana, sans-serif; font-size:23px; font-weight:700; line-height:23px; mso-text-raise:1px'>Verify your email</center> </v:roundrect></a>
        <![endif]--> <!--[if !mso]><!-- --><span class="es-button-border msohide" style="border-style:solid;border-color:#2CB543;background:#9357f4;border-width:0;display:inline-block;border-radius:5px;width:auto;mso-hide:all"><a href="https://resee.vercel.app/activate/${token.token}" class="es-button" target="_blank" style="mso-style-priority:100 !important;text-decoration:none !important;mso-line-height-rule:exactly;color:#FFFFFF;font-size:24px;padding:15px 35px;display:inline-block;background:#9357f4;border-radius:5px;font-family:helvetica, 'helvetica neue', arial, verdana, sans-serif;font-weight:bold;font-style:normal;line-height:29px;width:auto;text-align:center;letter-spacing:0;mso-padding-alt:0;mso-border-alt:10px solid #9357f4">Verify your email</a></span> <!--<![endif]--></td></tr><tr>
        <td align="left" class="es-text-2366" style="padding:0;Margin:0;padding-top:10px"><p align="center" style="Margin:0;mso-line-height-rule:exactly;font-family:helvetica, 'helvetica neue', arial, verdana, sans-serif;line-height:27px;letter-spacing:0;color:#333333;font-size:18px">If the button does not work, please use the link below:</p><p align="center" style="Margin:0;mso-line-height-rule:exactly;font-family:helvetica, 'helvetica neue', arial, verdana, sans-serif;line-height:27px;letter-spacing:0;color:#9357f4;font-size:18px" href="https://resee.vercel.app/activate/${token.token}"><a style="mso-line-height-rule:exactly;text-decoration:underline;color:#9357f4;font-size:18px;font-family:helvetica, 'helvetica neue', arial, verdana, sans-serif;line-height:27px" target="_blank" href="https://resee.vercel.app/activate/${token.token}">Verify your email</a></p></td> </tr><tr>
        <td align="left" class="es-text-6177" style="padding:0;Margin:0;padding-bottom:20px;padding-top:70px"><p align="center" style="Margin:0;mso-line-height-rule:exactly;font-family:helvetica, 'helvetica neue', arial, verdana, sans-serif;line-height:18px;letter-spacing:0;color:#666666;font-size:12px">This email was sent to you by resee because you signed up for a resee account. Please let us know if you feel that this email was sent to you by error.</p><p align="center" style="Margin:0;mso-line-height-rule:exactly;font-family:helvetica, 'helvetica neue', arial, verdana, sans-serif;line-height:18px;letter-spacing:0;color:#666666;font-size:12px">​</p><p align="center" style="Margin:0;mso-line-height-rule:exactly;font-family:helvetica, 'helvetica neue', arial, verdana, sans-serif;line-height:21px;letter-spacing:0;color:#9357f4;font-size:14px" class="es-text-mobile-size-14"><b>© 2024 resee Company</b></p></td></tr> </table></td></tr></table>
        </td></tr></table></td></tr></table></td></tr></table></div></body></html>`,
		recipentName: newAccount.name,
	})
}
